### ISSUE TITLE
Running on multi GPUs

### ISSUE THREAD

**Issue by salusanga** [IML-DKFZ/fd-shifts#3]
Hi,

thanks for the great work! I want to run the code on multiple A6000 GPUs, but when I start the training it crashes with the error: "_pickle.PicklingError: Can't pickle <class 'types.PartialBuilds_LinearWarmupCosineAnnealingLR'>: attribute lookup PartialBuilds_LinearWarmupCosineAnnealingLR on types failed" . 

Did you try running the code on multiple GPUs?
Thanks!
Best,
Sara

**Comment by tbung** [comment]
Hi, thank you for your interest in our project!

Did you use the Pytorch Lightning Trainer arguments to set up ddp? If so, did you explicitly select to use `ddp_spawn`? Because if I set `strategy="ddp"` in https://github.com/IML-DKFZ/fd-shifts/blob/main/fd_shifts/exec.py#L101 it works for me, at least on cpu. The `spawn` strategy has [several drawbacks](https://lightning.ai/docs/pytorch/1.6.5/accelerators/gpu.html#distributed-data-parallel), including the requirement that everything is picklable.

Let me know if that clears things up for you!

We will be releasing an updated version soon, that supports more recent versions of pytorch and lightning and should work better in a ddp setting.

**Comment by salusanga** [comment]
Hi,
thanks for the fast reply! Using ddp and commenting out the line setting the "spawn" option fixed the problem.
Best,
Sara
